import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { capabilityFlagOptions, coreConfigOptions, type CoreConfigKey } from '../src/config/options.js';
import { capabilityFlagsSchema, DEFAULT_CONFIG, type CapabilityKey } from '../src/config/schema.js';
import {
  CLOAKBROWSER_EXTRA_TOOL_COUNT,
  PLAYWRIGHT_MCP_BROWSER_TOOL_COUNT,
  PLAYWRIGHT_MCP_PACKAGE,
  PLAYWRIGHT_MCP_VERSION,
} from '../src/project/metadata.js';
import { mvpTools } from '../src/tools/index.js';

const generatedDocsDir = path.join(process.cwd(), '.generated-docs');

await mkdir(generatedDocsDir, { recursive: true });
await Promise.all([
  writeFile(path.join(generatedDocsDir, 'config-core-options.md'), renderCoreOptionsTable(), 'utf8'),
  writeFile(path.join(generatedDocsDir, 'config-capability-flags.md'), renderCapabilityFlagsTable(), 'utf8'),
  writeFile(path.join(generatedDocsDir, 'playwright-mcp-target.md'), renderPlaywrightMcpTarget(), 'utf8'),
  writeFile(
    path.join(generatedDocsDir, 'playwright-mcp-comparison.md'),
    renderPlaywrightMcpComparison(),
    'utf8',
  ),
]);

function renderCoreOptionsTable(): string {
  const lines = [
    '<!-- This file is generated by scripts/generate-config-docs.ts. Do not edit manually. -->',
    '',
    '| Option | Default | CLI flag | Environment variable | Description |',
    '| --- | --- | --- | --- | --- |',
    ...coreConfigOptions.map(
      (option) =>
        `| ${[
          code(option.key),
          formatDefault(option.key, 'defaultLabel' in option ? option.defaultLabel : undefined),
          code(option.cliFlag),
          code(option.envVar),
          escapeCell(option.description),
        ].join(' | ')} |`,
    ),
    '',
  ];
  return lines.join('\n');
}

function renderCapabilityFlagsTable(): string {
  const gatedTools = new Map<CapabilityKey, string[]>();
  for (const tool of mvpTools) {
    for (const capability of tool.capabilities ?? []) {
      const existing = gatedTools.get(capability) ?? [];
      existing.push(tool.name);
      gatedTools.set(capability, existing);
    }
  }
  const schemaKeys = Object.keys(capabilityFlagsSchema.shape).sort();
  const metadataKeys = capabilityFlagOptions.map((option) => option.key).sort();
  if (JSON.stringify(schemaKeys) !== JSON.stringify(metadataKeys)) {
    throw new Error('capabilityFlagOptions must cover every capabilityFlagsSchema key');
  }

  const lines = [
    '<!-- This file is generated by scripts/generate-config-docs.ts. Do not edit manually. -->',
    '',
    '| Flag | Default | Registered tools / guarded surface | Security implication |',
    '| --- | --- | --- | --- |',
    ...capabilityFlagOptions.map((option) => {
      const tools = gatedTools.get(option.key);
      const toolsLabel = tools?.length
        ? tools
            .sort()
            .map((name) => code(name))
            .join(', ')
        : 'fallbackToolsLabel' in option
          ? option.fallbackToolsLabel
          : '_none yet_';
      return `| ${[
        code(option.key),
        formatCapabilityDefault(option.key),
        toolsLabel,
        escapeCell(option.securityImplication),
      ].join(' | ')} |`;
    }),
    '',
  ];
  return lines.join('\n');
}

function renderPlaywrightMcpTarget(): string {
  return [
    '<!-- This file is generated by scripts/generate-config-docs.ts. Do not edit manually. -->',
    '',
    `The tool surface tracks ${code(PLAYWRIGHT_MCP_PACKAGE)} ${code(PLAYWRIGHT_MCP_VERSION)}. Shared tools accept Playwright-style ${code(
      'target',
    )} inputs as unique element selectors; this project also keeps the explicit ${code(
      'selector',
    )} alias for clarity. Human-readable ${code('element')}, ${code('name')}, and ${code(
      'type',
    )} fields are accepted where Playwright MCP sends them, but they are metadata only and are not used to locate elements.`,
    '',
    `Currently registered by default: **${
      PLAYWRIGHT_MCP_BROWSER_TOOL_COUNT + CLOAKBROWSER_EXTRA_TOOL_COUNT
    } tools** — the ${PLAYWRIGHT_MCP_BROWSER_TOOL_COUNT} Playwright MCP browser tools plus ${CLOAKBROWSER_EXTRA_TOOL_COUNT} project-specific tools.`,
    '',
  ].join('\n');
}

function renderPlaywrightMcpComparison(): string {
  return [
    '<!-- This file is generated by scripts/generate-config-docs.ts. Do not edit manually. -->',
    '',
    `Compared with ${code(PLAYWRIGHT_MCP_PACKAGE)} ${code(PLAYWRIGHT_MCP_VERSION)}:`,
    '',
  ].join('\n');
}

function formatDefault(key: CoreConfigKey, explicitLabel: string | undefined): string {
  if (explicitLabel) return explicitLabel;
  const value = (DEFAULT_CONFIG as Record<CoreConfigKey, unknown>)[key];
  if (Array.isArray(value)) return code(JSON.stringify(value));
  if (typeof value === 'string') return code(value);
  return code(String(value));
}

function formatCapabilityDefault(key: CapabilityKey): string {
  return DEFAULT_CONFIG.capabilities[key] ? '**on**' : 'off';
}

function code(value: string): string {
  return `\`${escapeCell(value)}\``;
}

function escapeCell(value: string): string {
  return value.replace(/\|/g, '\\|');
}
