import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { capabilityFlagOptions, coreConfigOptions } from '@/config/options.js';
import { PLAYWRIGHT_MCP_PACKAGE, PLAYWRIGHT_MCP_VERSION } from '@/project/metadata.js';

describe('configuration docs generation', () => {
  it('generates the core options table from config source metadata', () => {
    execFileSync('npm', ['run', 'docs:generate'], { cwd: process.cwd(), stdio: 'pipe' });

    const coreOptions = readFileSync(
      path.join(process.cwd(), '.generated-docs', 'config-core-options.md'),
      'utf8',
    );
    const capabilityFlags = readFileSync(
      path.join(process.cwd(), '.generated-docs', 'config-capability-flags.md'),
      'utf8',
    );
    const playwrightTarget = readFileSync(
      path.join(process.cwd(), '.generated-docs', 'playwright-mcp-target.md'),
      'utf8',
    );

    expect(coreOptions).toContain('generated by scripts/generate-config-docs.ts');
    for (const option of coreConfigOptions) {
      expect(coreOptions).toContain(`\`${option.key}\``);
      expect(coreOptions).toContain(`\`${option.envVar}\``);
    }
    for (const option of capabilityFlagOptions) {
      expect(capabilityFlags).toContain(`\`${option.key}\``);
    }
    expect(capabilityFlags).toContain('`browser_take_screenshot`');
    expect(playwrightTarget).toContain(`\`${PLAYWRIGHT_MCP_PACKAGE}\``);
    expect(playwrightTarget).toContain(`\`${PLAYWRIGHT_MCP_VERSION}\``);
  });
});
