name: Actionlint

on:
  push:
    branches: [main]
    paths:
      - .github/actionlint.yml
      - .github/workflows/**
  pull_request:
    paths:
      - .github/actionlint.yml
      - .github/workflows/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  ACTIONLINT_IMAGE_REF: docker.io/rhysd/actionlint:1.7.12@sha256:b1934ee5f1c509618f2508e6eb47ee0d3520686341fec936f3b79331f9315667

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run actionlint
        run: docker run --rm -v "$PWD:/repo" --workdir /repo "$ACTIONLINT_IMAGE_REF" -color
